In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('cleaned_LBW_Dataset.csv')

In [3]:
target = df.iloc[:, 9].to_numpy()

In [4]:
features = df.iloc[:, 0:9].to_numpy()

In [5]:
features

array([[ 1.        , 21.        , 42.        ,  1.        ,  9.2       ,
         1.        ,  1.375     ,  5.        ,  1.        ],
       [ 1.        , 21.        , 45.12941176,  1.        ,  8.8       ,
         1.        ,  1.5       ,  5.        ,  1.        ],
       [ 1.        , 21.        , 45.12941176,  1.        ,  9.2       ,
         1.        ,  2.125     ,  5.        ,  1.        ],
       [ 1.        , 21.        , 45.12941176,  1.        ,  8.        ,
         1.        ,  1.375     ,  5.        ,  1.        ],
       [ 1.        , 24.        , 33.        ,  1.        ,  9.3       ,
         1.        ,  1.571     ,  5.        ,  1.        ],
       [ 1.        , 26.        , 35.        ,  1.        ,  9.2       ,
         1.        ,  1.57142857,  5.        ,  1.        ],
       [ 4.        , 26.        , 31.        ,  1.        ,  9.07662338,
         1.        ,  1.625     ,  5.        ,  1.        ],
       [ 1.        , 22.        , 30.        ,  1.        ,  9

In [6]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.25, random_state = 7) 

In [7]:
X_train.shape[1]

9

In [8]:
df['Result'].value_counts().shape[0]

2

In [10]:
np.random.rand(2, 1)

array([[0.69478006],
       [0.82068539]])

In [40]:
wt = np.random.rand(1, X_train.shape[1])

In [42]:
wt = np.array(wt[0])

In [44]:
wt

array([0.21924656, 0.60057852, 0.21103839, 0.47340607, 0.60286294,
       0.30050803, 0.74284874, 0.86579003, 0.48935736])

In [19]:
np.dot(X_train, wt)

ValueError: shapes (1,9) and (72,9) not aligned: 9 (dim 1) != 72 (dim 0)

In [24]:
a = [[1, 0], [0, 1]]
b = [[4, 1]]

In [25]:
np.dot(a,b)

ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [37]:
for ele in X_train:
    print(ele)

[ 3.    25.    45.     1.     9.3    1.     1.375  5.     1.   ]
[ 3.    21.    55.     1.     9.     0.     1.375  5.     1.   ]
[ 1.         26.         60.          1.          9.2         0.
  1.71428571  5.          1.        ]
[ 4.         21.         37.          1.          9.07662338  1.
  1.375       5.          1.        ]
[ 2.    22.    40.     1.     8.9    1.     1.375  5.     1.   ]
[ 3.         35.         54.          1.          8.9         1.
  1.71428571  5.          1.        ]
[ 1.         24.         40.          1.          9.07662338  0.
  1.71184053  5.          1.        ]
[ 1.    26.    45.     1.     9.     1.     1.375  5.     1.   ]
[ 1.    21.    50.     1.     9.2    1.     1.625  5.     1.   ]
[ 1.         27.         45.12941176  1.          8.          1.
  1.57142857  5.          1.        ]
[ 4.    22.    50.     1.     9.2    1.     1.571  5.     1.   ]
[ 3.    21.    64.     1.     8.8    1.     1.666  5.     1.   ]
[ 1.    26.    43.     1.     

In [27]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1], dtype=int64)

In [28]:
l = [1,2,2,4]
ar = np.array(l)

In [29]:
ar

array([1, 2, 2, 4])

In [45]:
y_list = []
for ftr in X_train:
    y_list.append(np.dot(ftr, wt))

In [48]:
y = np.array(y_list)

In [53]:
y = y+1

In [56]:
y_train.shape

(72,)

In [55]:
y

array([38.38919428, 37.6158972 , 41.60809919, 34.38315414, 35.07187503,
       46.30521778, 36.10997873, 38.3704208 , 36.72900493, 38.54136394,
       37.94720929, 39.91134714, 37.94834402, 39.24301795, 36.42665912,
       40.93070195, 36.17364241, 36.2455629 , 36.77895564, 38.31001342,
       39.24803389, 42.73715371, 37.80237894, 38.28640263, 34.9039386 ,
       35.36712256, 35.73685494, 37.48531194, 38.15528934, 34.79197611,
       43.73828566, 38.77228419, 36.72083268, 40.14371144, 34.9632603 ,
       35.84274712, 36.43504342, 44.92992481, 39.94951813, 35.87099082,
       46.49919092, 36.68546699, 36.38281699, 43.03667602, 37.922179  ,
       36.83522292, 37.64014809, 37.3559578 , 41.14594329, 33.5653432 ,
       36.97932821, 36.30552857, 43.22639627, 37.45320856, 34.85498562,
       34.57850719, 33.14619315, 38.51561789, 35.53944434, 34.75082936,
       30.1568699 , 34.18660992, 40.82648142, 38.95818394, 35.61335466,
       36.68234184, 37.76666099, 35.38394453, 35.81480367, 36.03

In [59]:
Oy = 1//(1 + np.exp(-y))

In [69]:
Oy

array([1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0.])

In [87]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1], dtype=int64)

In [77]:
1//0.8

1.0

In [76]:
1/(1 + np.exp(-34.38315414))

0.9999999999999989

In [72]:
1 + np.exp(-38.38919428)

1.0

In [73]:
np.exp(-38.38919428)

2.127084581157463e-17

In [81]:
e  = (y_train - Oy)**2

In [85]:
(0.5)*e.sum()

15.0

In [86]:
(72-15)/72

0.7916666666666666

In [89]:
X_train.shape[0]

72